//! gRPC service for ingesting audit events.
//!
//! Implements a streaming RPC that accepts a stream of [`AuditEntryProto`]
//! messages, buffers them into batches, and writes each batch to PostgreSQL.

use std::pin::Pin;
use std::sync::Arc;

use chrono::{DateTime, Utc};
use tokio_stream::{Stream, StreamExt};
use tonic::{Request, Response, Status, Streaming};
use tracing::{error, info};

use crate::grpc::proto::{AuditEntryProto, IngestAck};
use crate::grpc::server::SharedState;
use crate::ledger::entry::{AuditEntryType, PendingEntry};
use crate::storage::postgres;
use crate::util::metrics;

// ---------------------------------------------------------------------------
// Service trait (would be generated by tonic-build from .proto)
// ---------------------------------------------------------------------------

/// Trait representing the IngestService gRPC interface.
#[tonic::async_trait]
pub trait IngestServiceRpc: Send + Sync + 'static {
    /// Server-streaming response for IngestEvents.
    type IngestEventsStream: Stream<Item = Result<IngestAck, Status>> + Send + 'static;

    /// Accept a stream of audit entries and return acknowledgements per batch.
    async fn ingest_events(
        &self,
        request: Request<Streaming<AuditEntryProto>>,
    ) -> Result<Response<Self::IngestEventsStream>, Status>;
}

// ---------------------------------------------------------------------------
// Service implementation
// ---------------------------------------------------------------------------

pub struct AuditIngestService {
    state: Arc<SharedState>,
}

impl AuditIngestService {
    pub fn new(state: Arc<SharedState>) -> Self {
        Self { state }
    }
}

#[tonic::async_trait]
impl IngestServiceRpc for AuditIngestService {
    type IngestEventsStream =
        Pin<Box<dyn Stream<Item = Result<IngestAck, Status>> + Send + 'static>>;

    async fn ingest_events(
        &self,
        request: Request<Streaming<AuditEntryProto>>,
    ) -> Result<Response<Self::IngestEventsStream>, Status> {
        let state = self.state.clone();
        let mut stream = request.into_inner();

        let output = async_stream::try_stream! {
            while let Some(msg) = stream.next().await {
                let proto = msg?;

                let entry_type = AuditEntryType::from_i16(proto.entry_type as i16)
                    .ok_or_else(|| Status::invalid_argument(
                        format!("unknown entry_type: {}", proto.entry_type),
                    ))?;

                let timestamp = DateTime::from_timestamp_millis(proto.timestamp_unix_ms)
                    .unwrap_or_else(Utc::now);

                let pending = PendingEntry {
                    entry_type,
                    timestamp,
                    gpu_uuid: proto.gpu_uuid,
                    sm_id: proto.sm_id,
                    data: proto.data,
                };

                let should_flush = {
                    let mut acc = state.accumulator.lock().await;
                    acc.push(pending)
                };

                if should_flush {
                    let ack = flush_batch(&state).await.map_err(|e| {
                        error!(error = %e, "batch flush failed");
                        Status::internal(format!("batch flush failed: {e}"))
                    })?;
                    yield ack;
                }
            }

            // Flush any remaining entries when the stream closes.
            let remaining = {
                let acc = state.accumulator.lock().await;
                !acc.is_empty()
            };
            if remaining {
                let ack = flush_batch(&state).await.map_err(|e| {
                    error!(error = %e, "final batch flush failed");
                    Status::internal(format!("final batch flush failed: {e}"))
                })?;
                yield ack;
            }
        };

        Ok(Response::new(Box::pin(output)))
    }
}

/// Drain the accumulator, build a chained batch, write to PostgreSQL, and
/// return an acknowledgement.
async fn flush_batch(state: &SharedState) -> anyhow::Result<IngestAck> {
    let pending = {
        let mut acc = state.accumulator.lock().await;
        acc.drain()
    };

    if pending.is_empty() {
        return Ok(IngestAck {
            batch_sequence: 0,
            entry_count: 0,
            merkle_root: vec![],
        });
    }

    let entry_count = pending.len() as u64;
    let batch = {
        let mut builder = state.chain_builder.lock().await;
        builder.build_batch(pending)
    };

    postgres::insert_batch(&state.pool, &batch).await?;

    metrics::AUDIT_ENTRIES_TOTAL.inc_by(entry_count);
    metrics::AUDIT_BATCHES_TOTAL.inc();

    info!(
        batch_sequence = batch.batch_sequence,
        entries = entry_count,
        "Batch committed"
    );

    Ok(IngestAck {
        batch_sequence: batch.batch_sequence,
        entry_count,
        merkle_root: batch.merkle_root.to_vec(),
    })
}

// ---------------------------------------------------------------------------
// tonic service wrapper (normally generated)
// ---------------------------------------------------------------------------
//
// `AuditIngestServer` would normally be generated by `tonic-build` from the
// `.proto` definition.  The generated type implements `tower::Service` and
// `tonic::server::NamedService`, which allows it to be registered with
// `tonic::transport::Server::add_service`.
//
// Until the proto compilation pipeline is in place, the service
// *implementation* above (`AuditIngestService`) is kept ready so that it can
// be plugged into the generated server type with no further changes.
