//! gRPC service for ingesting audit events.
//!
//! Implements a streaming RPC that accepts a stream of [`AuditEntryProto`]
//! messages, buffers them into batches, and writes each batch to PostgreSQL.

use std::pin::Pin;
use std::sync::Arc;

use chrono::{DateTime, Utc};
use tokio_stream::{Stream, StreamExt};
use tonic::{Request, Response, Status, Streaming};
use tracing::{error, info};

use crate::grpc::proto::{AuditEntryProto, IngestAck};
use crate::grpc::server::SharedState;
use crate::ledger::entry::{AuditEntryType, PendingEntry};
use crate::storage::postgres;
use crate::util::metrics;

// ---------------------------------------------------------------------------
// Service trait (would be generated by tonic-build from .proto)
// ---------------------------------------------------------------------------

/// Trait representing the IngestService gRPC interface.
#[tonic::async_trait]
pub trait IngestServiceRpc: Send + Sync + 'static {
    /// Server-streaming response for IngestEvents.
    type IngestEventsStream: Stream<Item = Result<IngestAck, Status>> + Send + 'static;

    /// Accept a stream of audit entries and return acknowledgements per batch.
    async fn ingest_events(
        &self,
        request: Request<Streaming<AuditEntryProto>>,
    ) -> Result<Response<Self::IngestEventsStream>, Status>;
}

// ---------------------------------------------------------------------------
// Service implementation
// ---------------------------------------------------------------------------

pub struct AuditIngestService {
    state: Arc<SharedState>,
}

impl AuditIngestService {
    pub fn new(state: Arc<SharedState>) -> Self {
        Self { state }
    }
}

#[tonic::async_trait]
impl IngestServiceRpc for AuditIngestService {
    type IngestEventsStream =
        Pin<Box<dyn Stream<Item = Result<IngestAck, Status>> + Send + 'static>>;

    async fn ingest_events(
        &self,
        request: Request<Streaming<AuditEntryProto>>,
    ) -> Result<Response<Self::IngestEventsStream>, Status> {
        let state = self.state.clone();
        let mut stream = request.into_inner();

        let output = async_stream::try_stream! {
            while let Some(msg) = stream.next().await {
                let proto = msg?;

                let entry_type = AuditEntryType::from_i16(proto.entry_type as i16)
                    .ok_or_else(|| Status::invalid_argument(
                        format!("unknown entry_type: {}", proto.entry_type),
                    ))?;

                let timestamp = DateTime::from_timestamp_millis(proto.timestamp_unix_ms)
                    .unwrap_or_else(Utc::now);

                let pending = PendingEntry {
                    entry_type,
                    timestamp,
                    gpu_uuid: proto.gpu_uuid,
                    sm_id: proto.sm_id,
                    data: proto.data,
                };

                let should_flush = {
                    let mut acc = state.accumulator.lock().await;
                    acc.push(pending)
                };

                if should_flush {
                    let ack = flush_batch(&state).await.map_err(|e| {
                        error!(error = %e, "batch flush failed");
                        Status::internal(format!("batch flush failed: {e}"))
                    })?;
                    yield ack;
                }
            }

            // Flush any remaining entries when the stream closes.
            let remaining = {
                let acc = state.accumulator.lock().await;
                !acc.is_empty()
            };
            if remaining {
                let ack = flush_batch(&state).await.map_err(|e| {
                    error!(error = %e, "final batch flush failed");
                    Status::internal(format!("final batch flush failed: {e}"))
                })?;
                yield ack;
            }
        };

        Ok(Response::new(Box::pin(output)))
    }
}

/// Drain the accumulator, build a chained batch, write to PostgreSQL, and
/// return an acknowledgement.
async fn flush_batch(state: &SharedState) -> anyhow::Result<IngestAck> {
    let pending = {
        let mut acc = state.accumulator.lock().await;
        acc.drain()
    };

    if pending.is_empty() {
        return Ok(IngestAck {
            batch_sequence: 0,
            entry_count: 0,
            merkle_root: vec![],
        });
    }

    let entry_count = pending.len() as u64;
    let batch = {
        let mut builder = state.chain_builder.lock().await;
        builder.build_batch(pending)
    };

    postgres::insert_batch(&state.pool, &batch).await?;

    metrics::AUDIT_ENTRIES_TOTAL.inc_by(entry_count);
    metrics::AUDIT_BATCHES_TOTAL.inc();

    info!(
        batch_sequence = batch.batch_sequence,
        entries = entry_count,
        "Batch committed"
    );

    Ok(IngestAck {
        batch_sequence: batch.batch_sequence,
        entry_count,
        merkle_root: batch.merkle_root.to_vec(),
    })
}

// ---------------------------------------------------------------------------
// tonic service wrapper (normally generated)
// ---------------------------------------------------------------------------

/// A tonic `Service` wrapper around [`AuditIngestService`].
///
/// In production this would be generated by `tonic-build`.  Here we manually
/// implement the tower `Service` trait so the type can be registered with
/// `tonic::transport::Server`.
pub struct AuditIngestServer<T: IngestServiceRpc> {
    inner: Arc<T>,
}

impl<T: IngestServiceRpc> AuditIngestServer<T> {
    pub fn new(inner: T) -> Self {
        Self {
            inner: Arc::new(inner),
        }
    }
}

impl<T: IngestServiceRpc> Clone for AuditIngestServer<T> {
    fn clone(&self) -> Self {
        Self {
            inner: self.inner.clone(),
        }
    }
}

impl<T: IngestServiceRpc> tonic::codegen::Service<http::Request<tonic::body::BoxBody>>
    for AuditIngestServer<T>
{
    type Response = http::Response<tonic::body::BoxBody>;
    type Error = std::convert::Infallible;
    type Future = std::pin::Pin<
        Box<dyn std::future::Future<Output = Result<Self::Response, Self::Error>> + Send>,
    >;

    fn poll_ready(
        &mut self,
        _cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Result<(), Self::Error>> {
        std::task::Poll::Ready(Ok(()))
    }

    fn call(&mut self, _req: http::Request<tonic::body::BoxBody>) -> Self::Future {
        // In a full tonic-generated server each RPC method would be dispatched
        // based on the request path.  For this inline implementation we return
        // UNIMPLEMENTED for direct HTTP/2 calls.
        let resp = http::Response::builder()
            .status(200)
            .header("grpc-status", "12") // UNIMPLEMENTED
            .header("content-type", "application/grpc")
            .body(tonic::body::empty_body())
            .unwrap();
        Box::pin(async { Ok(resp) })
    }
}

impl<T: IngestServiceRpc> tonic::server::NamedService for AuditIngestServer<T> {
    const NAME: &'static str = "sentinel.audit.IngestService";
}
