//! gRPC server bootstrap.
//!
//! Starts the gRPC transport and registers service implementations.
//!
//! The service wrapper types (`AuditIngestServer`, `AuditQueryServer`) would
//! normally be generated by `tonic-build` from `.proto` files.  Until the proto
//! compilation pipeline is wired up the server starts with an empty router and
//! the service *implementations* (which live in `ingest_service` /
//! `query_service`) are kept ready for integration.

use std::net::SocketAddr;
use std::sync::Arc;

use anyhow::Result;
use sqlx::PgPool;
use tokio::sync::Mutex;
use tracing::info;

use crate::ledger::merkle_chain::{BatchAccumulator, ChainBuilder};

/// Shared state passed to gRPC service implementations.
pub struct SharedState {
    pub pool: PgPool,
    pub chain_builder: Mutex<ChainBuilder>,
    pub accumulator: Mutex<BatchAccumulator>,
}

/// Start the gRPC server.
///
/// Once `tonic-build` generates `AuditIngestServer` and `AuditQueryServer`
/// from the `.proto` files, this function will register them with
/// `tonic::transport::Server::add_service(...)`.
///
/// Until then we bind a TCP listener on the configured address so the rest of
/// the application (background workers, metrics) can start normally.
pub async fn start(addr: SocketAddr, pool: PgPool, chain_builder: ChainBuilder) -> Result<()> {
    // Build shared state that service implementations will use.
    let _state = Arc::new(SharedState {
        pool: pool.clone(),
        chain_builder: Mutex::new(chain_builder),
        accumulator: Mutex::new(BatchAccumulator::default_config()),
    });

    info!(%addr, "Starting gRPC server (awaiting proto codegen for service registration)");

    // TODO: register tonic services once proto-generated server types exist:
    //
    //   use tonic::transport::Server;
    //   let ingest = generated::AuditIngestServer::new(
    //       AuditIngestService::new(state.clone()));
    //   let query  = generated::AuditQueryServer::new(
    //       AuditQueryService::new(state));
    //   Server::builder()
    //       .add_service(ingest)
    //       .add_service(query)
    //       .serve(addr)
    //       .await?;

    // Placeholder: bind a TCP listener so the port is held open.
    let listener = tokio::net::TcpListener::bind(addr)
        .await
        .map_err(|e| anyhow::anyhow!("failed to bind {addr}: {e}"))?;

    info!(%addr, "gRPC listener ready");

    // Accept (and immediately drop) connections until the process is shut down.
    loop {
        if let Err(e) = listener.accept().await {
            tracing::warn!(error = %e, "accept error on gRPC listener");
        }
    }
}
