"""SENTINEL SDK -- Python client for the SENTINEL Silent Data Corruption detection framework."""

from sentinel_sdk.client import (
    AuthenticationError,
    ConnectionError,
    InvalidArgumentError,
    NotFoundError,
    RetryConfig,
    SentinelClient,
    SentinelError,
    TlsConfig,
)
from sentinel_sdk.types import (
    AnomalyEvent,
    AnomalySource,
    AnomalyType,
    ApprovalStatus,
    AuditEntry,
    AuditEntryType,
    AuditQueryFilters,
    AuditQueryResponse,
    ChainVerificationResult,
    ConfigAck,
    ConfigUpdate,
    CorrelationEvent,
    DirectiveResponse,
    EccCounters,
    FleetHealthSummary,
    GpuHealth,
    GpuHealthState,
    GpuHistoryResponse,
    GpuIdentifier,
    GpuTelemetryReport,
    MismatchDetail,
    NvLinkStatus,
    OverheadBudgetUpdate,
    PatternType,
    PowerReading,
    ProbeExecution,
    ProbeResult,
    ProbeScheduleEntry,
    ProbeScheduleOverride,
    ProbeScheduleUpdate,
    ProbeType,
    QuarantineAction,
    QuarantineDirective,
    ReliabilitySample,
    SamplingRateUpdate,
    Severity,
    SmHealth,
    SmIdentifier,
    StateTransition,
    ThermalReading,
    ThresholdUpdate,
    TmrGpuResult,
    TmrResult,
    TrustEdge,
    TrustGraphSnapshot,
)

__all__ = [
    # Client
    "SentinelClient",
    "TlsConfig",
    "RetryConfig",
    # Exceptions
    "SentinelError",
    "ConnectionError",
    "AuthenticationError",
    "NotFoundError",
    "InvalidArgumentError",
    # Common
    "GpuIdentifier",
    "SmIdentifier",
    "Severity",
    # Probe
    "ProbeType",
    "ProbeResult",
    "MismatchDetail",
    "ProbeExecution",
    "ProbeScheduleOverride",
    # Anomaly
    "AnomalyType",
    "AnomalySource",
    "AnomalyEvent",
    # Health
    "GpuHealthState",
    "GpuHealth",
    "SmHealth",
    "FleetHealthSummary",
    # Trust
    "TrustEdge",
    "TrustGraphSnapshot",
    "TmrGpuResult",
    "TmrResult",
    # Quarantine
    "QuarantineAction",
    "ApprovalStatus",
    "QuarantineDirective",
    "DirectiveResponse",
    # Correlation
    "PatternType",
    "CorrelationEvent",
    "StateTransition",
    "ReliabilitySample",
    "GpuHistoryResponse",
    # Audit
    "AuditEntryType",
    "AuditEntry",
    "ChainVerificationResult",
    "AuditQueryFilters",
    "AuditQueryResponse",
    # Config
    "ProbeScheduleEntry",
    "ProbeScheduleUpdate",
    "OverheadBudgetUpdate",
    "SamplingRateUpdate",
    "ThresholdUpdate",
    "ConfigUpdate",
    "ConfigAck",
    # Telemetry
    "ThermalReading",
    "PowerReading",
    "EccCounters",
    "NvLinkStatus",
    "GpuTelemetryReport",
]

__version__ = "0.1.0"
